apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: demowebappregistry.azurecr.io/demowebappimage:v1
        ports: 
        - containerPort: 80
        # env:
        # - name: MSSQL_SERVICE_HOST
        #   value: mssql-service # The name of your MSSQL ClusterIP service
        # - name: MSSQL_SERVICE_PORT
        #   value: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - name: webapp-port
    protocol: TCP
    port: 8080
    targetPort: 80
